# Generated by Django 6.0.2 on 2026-02-25 09:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytic_core', '0002_visitor'),
    ]

    operations = [
        migrations.CreateModel(
            name='session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=100)),
                ('user_agent', models.TextField()),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(auto_now=True)),
                ('duration', models.IntegerField()),
                ('browser', models.CharField(max_length=100)),
                ('device', models.CharField(max_length=100)),
                ('os', models.CharField(max_length=100)),
                ('is_bot', models.BooleanField(default=False)),
                ('site_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytic_core.trackedsite')),
                ('visitor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytic_core.visitor')),
            ],
        ),
        migrations.CreateModel(
            name='pageview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('page_url', models.CharField(max_length=100)),
                ('page_title', models.CharField(max_length=100)),
                ('page_view_time', models.DateTimeField(auto_now_add=True)),
                ('session_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytic_core.session')),
            ],
        ),
    ]
