# Generated by Django 6.0.2 on 2026-02-25 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytic_core', '0003_session_pageview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='pageview',
        ),
    ]
