# Generated by Django 6.0.2 on 2026-02-25 09:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytic_core', '0004_delete_pageview'),
    ]

    operations = [
        migrations.CreateModel(
            name='pageview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('page_url', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytic_core.session')),
            ],
        ),
    ]
