# Generated by Django 4.2.1 on 2026-02-25 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytic_core', '0005_pageview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackedsite',
            name='api_key',
            field=models.CharField(blank=True, db_index=True, max_length=100, unique=True),
        ),
    ]
