# Generated by Django 4.2.1 on 2026-02-25 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytic_core', '0007_fix_session_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageview',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pageview',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
