# Generated by Django 4.2.1 on 2026-02-26 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytic_core', '0008_upgrade_pageview_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
