# Generated by Django 6.0.2 on 2026-02-26 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytic_core', '0009_session_last_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageview',
            name='site_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='analytic_core.trackedsite'),
        ),
        migrations.AddField(
            model_name='pageview',
            name='site_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='site_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='site_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
