# Generated by Django 4.2.7 on 2026-03-04 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analytic_core', '0010_pageview_site_id_pageview_site_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackedsite',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
