# Generated by Django 4.2.7 on 2026-03-04 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytic_core', '0011_trackedsite_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackedsite',
            name='user',
        ),
        migrations.AlterField(
            model_name='pageview',
            name='page_url',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='session',
            name='country',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='is_bot',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='visitor_id',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
